---
version: '3'
---
---
networks:
  default:
    external:
      name: ramias
---
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_laravel
    ports:
      - "7000:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/certs
    depends_on:
      - php
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql_laravel
    restart: unless-stopped
    tty: true
    ports:
      - "9306:3306"
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_db
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_laravel
    volumes:
      - ./:/var/www/html
    ports:
      - "9004:9004"

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan_laravel
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']

  redis:
    image: redis
    container_name: redis_laravel
    ports:
      - "6379:6379"

  memcached:
    container_name: memcached_laravel
    image: memcached:latest
    ports:
      - "11211:11211"
